services:
  api1:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api1
    environment:
      WORKERS: '4'
      SOCKET_PATH: '/tmp/app1.sock'
    volumes:
      - uds_sockets:/tmp
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.40"
    #       memory: "130MB"
    networks:
      - rinha-net

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api2
    environment:
      WORKERS: '4'
      SOCKET_PATH: '/tmp/app2.sock'
    volumes:
      - uds_sockets:/tmp
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.40"
    #       memory: "130MB"
    networks:
      - rinha-net

  haproxy:
    image: haproxy:3.0-alpine
    ports:
      - '9999:9999'
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - uds_sockets:/tmp
    depends_on:
      - api1
      - api2
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.20"
    #       memory: "90MB"
    networks:
      - rinha-net

networks:
  rinha-net:
    driver: bridge

volumes:
  uds_sockets:
