name: rinha-backend

services:
  load-balancer:
    platform: linux/amd64
    image: ghcr.io/cirilord/rinha-backend-2026-lb:sha-a67b370d83472a134b7cc2a00657ab16828874a1
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    cpus: 0.2
    mem_limit: 20m
    environment:
      UPSTREAM_SOCKETS: "/tmp/server-1.sock,/tmp/server-2.sock"
    logging:
      driver: none
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - sockets:/tmp
    networks:
      - rinha

  api1:
    platform: linux/amd64
    image: ghcr.io/cirilord/rinha-backend-2026-api:sha-a67b370d83472a134b7cc2a00657ab16828874a1
    command: ["/tmp/server-1.sock"]
    cpus: 0.4
    mem_limit: 165m
    environment:
      CONN_POOL_CAP: "512"
      EPOLL_SPIN_US: "0"
      EPOLL_IDLE_US: "60"
      EPOLL_BUSY_POLL_US: "100"
      EPOLL_BUSY_POLL_BUDGET: "8"
      EPOLL_PREFER_BUSY_POLL: "1"
    logging:
      driver: none
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - sockets:/tmp
    networks:
      - rinha

  api2:
    platform: linux/amd64
    image: ghcr.io/cirilord/rinha-backend-2026-api:sha-a67b370d83472a134b7cc2a00657ab16828874a1
    command: ["/tmp/server-2.sock"]
    cpus: 0.4
    mem_limit: 165m
    environment:
      CONN_POOL_CAP: "512"
      EPOLL_SPIN_US: "0"
      EPOLL_IDLE_US: "60"
      EPOLL_BUSY_POLL_US: "100"
      EPOLL_BUSY_POLL_BUDGET: "8"
      EPOLL_PREFER_BUSY_POLL: "1"
    logging:
      driver: none
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - sockets:/tmp
    networks:
      - rinha

volumes:
  sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=4m,uid=0,gid=0,mode=0777"

networks:
  rinha:
    driver: bridge
