services:
  api1:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    environment:
      UNIX_SOCKET_PATH: "/shared/api1.sock"
      X_SCORE_INDEX_PATH: "/app/resources/references.idx"
    volumes:
      - shared-sockets:/shared
    networks:
      - rinha

  api2:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    environment:
      UNIX_SOCKET_PATH: "/shared/api2.sock"
      X_SCORE_INDEX_PATH: "/app/resources/references.idx"
    volumes:
      - shared-sockets:/shared
    networks:
      - rinha

  load-balancer:
    build:
      context: ./apps/load-balancer
    ports:
      - "9999:9999"
    environment:
      PORT: "9999"
      WORKER_SOCKETS: "/shared/api1.sock,/shared/api2.sock"
    volumes:
      - shared-sockets:/shared
    depends_on:
      - api1
      - api2
    networks:
      - rinha

networks:
  rinha:
    driver: bridge

volumes:
  shared-sockets:
