services:
  # api1:
  #   image: __API_IMAGE__
  #   environment:
  #     UNIX_SOCKET_PATH: "/shared/api1.sock"
  #     X_SCORE_INDEX_PATH: "/app/resources/references.idx"
  #   volumes:
  #     - shared-sockets:/shared
  #   ulimits:
  #     nofile:
  #       soft: 65535
  #       hard: 65535
  #   networks:
  #     - rinha
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.44"
  #         memory: "150MB"
  #
  # api2:
  #   image: __API_IMAGE__
  #   environment:
  #     UNIX_SOCKET_PATH: "/shared/api2.sock"
  #     X_SCORE_INDEX_PATH: "/app/resources/references.idx"
  #   volumes:
  #     - shared-sockets:/shared
  #   ulimits:
  #     nofile:
  #       soft: 65535
  #       hard: 65535
  #   networks:
  #     - rinha
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.44"
  #         memory: "150MB"
  #
  # load-balancer:
  #   image: __LB_IMAGE__
  #   ports:
  #     - "9999:9999"
  #   environment:
  #     PORT: "9999"
  #     WORKER_SOCKETS: "/shared/api1.sock,/shared/api2.sock"
  #   volumes:
  #     - shared-sockets:/shared
  #   ulimits:
  #     nofile:
  #       soft: 65535
  #       hard: 65535
  #   depends_on:
  #     - api1
  #     - api2
  #   networks:
  #     - rinha
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.12"
  #         memory: "50MB"

  server3-1:
    image: __API_IMAGE__
    environment:
      UNIX_SOCKET_PATH: "/shared/server3-1.sock"
      X_SCORE_INDEX_PATH: "/app/resources/references.idx"
    volumes:
      - shared-sockets:/shared
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    cpuset: "1"
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.42"
          memory: "150MB"

  server3-2:
    image: __API_IMAGE__
    environment:
      UNIX_SOCKET_PATH: "/shared/server3-2.sock"
      X_SCORE_INDEX_PATH: "/app/resources/references.idx"
    volumes:
      - shared-sockets:/shared
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    cpuset: "2"
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.42"
          memory: "150MB"

  lb3:
    image: __LB_IMAGE__
    ports:
      - "9999:9999"
    environment:
      PORT: "9999"
      WORKER_SOCKETS: "/shared/server3-1.sock,/shared/server3-2.sock"
    volumes:
      - shared-sockets:/shared
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    cpuset: "0"
    depends_on:
      - server3-1
      - server3-2
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.16"
          memory: "50MB"

networks:
  rinha:
    driver: bridge

volumes:
  shared-sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=4m,mode=0777
